apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-service-7o7y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-service-7o7y
    app.kubernetes.io/part-of: build-service
  name: build-service-7o7y
  namespace: rhn-support-bpimente-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-service-7o7y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-service-7o7y
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:rhn-support-bpimente-tenant-build-service-7o7y
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
