apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: build-service
    appstudio.openshift.io/component: build-service-7o7y
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: build-service-7o7y
  namespace: rhn-support-bpimente-tenant
spec:
  url: https://github.com/brunoapimentel/build-service
